"""Generates data/books.json and data/tbr.json (source of truth for the book data)."""
import json

G = {
  "prod": ("Productivity", "Produtividade"),
  "self": ("Self-Improvement", "Desenvolvimento pessoal"),
  "mkt": ("Marketing", "Marketing"),
  "ent": ("Entrepreneurship", "Empreendedorismo"),
  "write": ("Writing", "Escrita"),
  "sci": ("Science", "Ciência"),
  "psy": ("Psychology", "Psicologia"),
  "fin": ("Finance", "Finanças"),
  "health": ("Health", "Saúde"),
  "tech": ("Technology & AI", "Tecnologia e IA"),
  "fic": ("Science Fiction", "Ficção científica"),
  "photo": ("Photography", "Fotografia"),
  "film": ("Film", "Cinema"),
  "career": ("Career", "Carreira"),
  "create": ("Creativity & Thinking", "Criatividade e pensamento"),
}

def b(slug, title, author, year, g, en, pt, fmt, title_pt=None, **extra):
    d = {"slug": slug, "title": title}
    if title_pt: d["title_pt"] = title_pt
    d.update({"author": author, "year": year,
              "genre": G[g][0], "genre_pt": G[g][1],
              "synopsis": en, "synopsis_pt": pt,
              "format": fmt, "image": f"images/covers/{slug}.jpg"})
    d.update(extra)
    return d

READ = [
 b("atomic-habits","Atomic Habits","James Clear",2018,"self",
   "A practical framework for building good habits and breaking bad ones through tiny changes that compound over time, built on four laws: make it obvious, attractive, easy and satisfying.",
   "Um método prático para criar bons hábitos e abandonar os ruins por meio de pequenas mudanças que se acumulam com o tempo, baseado em quatro leis: tornar óbvio, atraente, fácil e satisfatório.",
   "Physical", "Hábitos Atômicos", rating=4.5, status="highlighted"),
 b("varieties-of-scientific-experience","The Varieties of Scientific Experience","Carl Sagan",2006,"sci",
   "Sagan's 1985 Gifford Lectures, published posthumously: a personal view on science, the cosmos and the search for God, arguing for wonder grounded in evidence.",
   "As Palestras Gifford de Sagan, de 1985, publicadas postumamente: uma visão pessoal sobre ciência, cosmos e a busca por Deus, defendendo o deslumbramento baseado em evidências.",
   "Libby", "Variedades da Experiência Científica", status="reading"),
 b("crush-it","Crush It!","Gary Vaynerchuk",2009,"ent",
   "Gary Vee's call to turn your passion into a business by building a personal brand on social media, and the hustle it takes to make it work.",
   "O chamado de Gary Vee para transformar sua paixão em negócio construindo uma marca pessoal nas redes sociais, e o trabalho duro necessário para fazer isso dar certo.",
   "Physical", rating=4.0, status="distilled"),
 b("how-to-take-smart-notes","How to Take Smart Notes","Sönke Ahrens",2017,"prod",
   "An introduction to the Zettelkasten method: how a slip-box of connected, permanent notes turns reading into writing and thinking into a routine.",
   "Uma introdução ao método Zettelkasten: como um arquivo de notas permanentes e conectadas transforma a leitura em escrita e o pensamento em rotina.",
   "Libby", "Como Fazer Anotações Inteligentes", rating=5.0, status="highlighted"),
 b("building-a-second-brain","Building a Second Brain","Tiago Forte",2022,"prod",
   "A methodology for capturing, organizing and sharing what you learn in a digital system (CODE and PARA), so your ideas become finished work.",
   "Uma metodologia para capturar, organizar e compartilhar o que você aprende em um sistema digital (CODE e PARA), transformando ideias em trabalho concluído.",
   "Physical", "Construindo um Segundo Cérebro", rating=5.0, status="distilled"),
 b("purple-cow","Purple Cow","Seth Godin",2003,"mkt",
   "Why being remarkable is the only safe marketing strategy: stop blending in with the herd and build products worth talking about.",
   "Por que ser notável é a única estratégia de marketing segura: pare de se misturar à manada e crie produtos dignos de comentário.",
   "Physical", "Vaca Roxa", rating=4.0, status="highlighted"),
 b("essentialism","Essentialism","Greg McKeown",2014,"prod",
   "The disciplined pursuit of less: how to separate the vital few from the trivial many and say no to everything that isn't essential.",
   "A busca disciplinada por menos: como separar os poucos itens vitais dos muitos triviais e dizer não a tudo que não é essencial.",
   "Physical", "Essencialismo", rating=4.5, status="highlighted"),
 b("psychology-of-money","The Psychology of Money","Morgan Housel",2020,"fin",
   "Nineteen short stories on how behavior, not intelligence, drives financial outcomes, and what timeless lessons say about wealth, greed and happiness.",
   "Dezenove histórias curtas sobre como o comportamento, e não a inteligência, define os resultados financeiros, e o que lições atemporais dizem sobre riqueza, ganância e felicidade.",
   "Libby", "A Psicologia Financeira", rating=4.0, status="highlighted"),
 b("slow-productivity","Slow Productivity","Cal Newport",2024,"prod",
   "The lost art of accomplishment without burnout, built on three principles: do fewer things, work at a natural pace, and obsess over quality.",
   "A arte perdida de realizar sem se esgotar, baseada em três princípios: fazer menos coisas, trabalhar em um ritmo natural e ser obcecado por qualidade.",
   "Physical", rating=4.0, status="read"),
 b("feel-good-productivity","Feel-Good Productivity","Ali Abdaal",2023,"prod",
   "How to do more of what matters by boosting energy rather than forcing discipline, using a framework of play, power and people.",
   "Como fazer mais do que importa aumentando a energia em vez de forçar a disciplina, usando um modelo de diversão, poder e pessoas.",
   "Physical", rating=4.0, status="read"),
 b("getting-things-done","Getting Things Done","David Allen",2001,"prod",
   "The classic system for stress-free productivity: capture everything, clarify what it means, organize it and review it regularly.",
   "O sistema clássico de produtividade sem estresse: capturar tudo, esclarecer o que significa, organizar e revisar regularmente.",
   "Libby", "A Arte de Fazer Acontecer", status="reading"),
 b("deep-work","Deep Work","Cal Newport",2016,"prod",
   "Rules for focused success in a distracted world: why the ability to concentrate without distraction is rare, valuable and trainable.",
   "Regras para o sucesso focado em um mundo distraído: por que a capacidade de se concentrar sem distração é rara, valiosa e treinável.",
   "Libby", "Trabalho Focado", status="reading"),
 b("sense-of-style","The Sense of Style","Steven Pinker",2014,"write",
   "A cognitive scientist's guide to clear, elegant writing in the 21st century, drawing on linguistics and psychology instead of rigid rules.",
   "O guia de um cientista cognitivo para escrever com clareza e elegância no século XXI, com base em linguística e psicologia em vez de regras rígidas.",
   "Libby", "Guia de Escrita", status="reading"),
 b("storynomics","Storynomics","Robert McKee & Thomas Gerace",2018,"mkt",
   "Story-driven marketing in the post-advertising world: how to use the principles of great storytelling to build brands people care about.",
   "Marketing orientado por histórias no mundo pós-publicidade: como usar os princípios do bom storytelling para construir marcas que importam para as pessoas.",
   "Libby", status="reading"),
]

TBR = [
 b("rise-of-the-youpreneur","Rise of the Youpreneur","Chris Ducker",2018,"ent",
   "A guide to building a personal-brand business around who you are, from finding your audience to creating products and a loyal community.",
   "Um guia para construir um negócio de marca pessoal em torno de quem você é, desde encontrar seu público até criar produtos e uma comunidade fiel.","Physical"),
 b("primal-branding","Primalbranding","Patrick Hanlon",2006,"mkt",
   "Argues that strong brands are belief systems, and lays out seven elements (creation story, creed, icon, rituals, sacred words, nonbelievers and leader) that create devoted communities.",
   "Defende que marcas fortes são sistemas de crenças e apresenta sete elementos (história de origem, credo, ícone, rituais, palavras sagradas, não crentes e líder) que criam comunidades devotas.","Physical"),
 b("business-for-punks","Business for Punks","James Watt",2015,"ent",
   "The BrewDog co-founder's playbook for breaking the rules of business: build a brand with attitude, ignore convention and take on the giants.",
   "O manual do cofundador da BrewDog para quebrar as regras dos negócios: construir uma marca com atitude, ignorar convenções e enfrentar os gigantes.","Physical"),
 b("sell-like-crazy","Sell Like Crazy","Sabri Suby",2019,"mkt",
   "An Australian growth marketer's step-by-step system for generating leads and sales online, with direct-response tactics and a focus on measurable results.",
   "O sistema passo a passo de um especialista australiano em crescimento para gerar leads e vendas online, com táticas de resposta direta e foco em resultados mensuráveis.","Physical"),
 b("inner-game-of-tennis","The Inner Game of Tennis","W. Timothy Gallwey",1974,"self",
   "A classic on the mental side of performance: quiet the self-critical mind, trust your body and learn through awareness instead of instruction.",
   "Um clássico sobre o lado mental do desempenho: silenciar a mente autocrítica, confiar no corpo e aprender pela percepção em vez de pela instrução.","Physical","O Jogo Interior de Tênis"),
 b("great-photographs","Read This if You Want to Take Great Photographs","Henry Carroll",2014,"photo",
   "A short visual primer that teaches composition, light, exposure and more through the work of great photographers, with no jargon.",
   "Um guia visual e enxuto que ensina composição, luz, exposição e mais por meio do trabalho de grandes fotógrafos, sem jargão técnico.","Physical"),
 b("this-is-how-you-make-a-movie","This Is How You Make a Movie","Tim Grierson",2021,"film",
   "An accessible, illustrated guide to how films get made, from the initial idea and script through casting, shooting, editing and release.",
   "Um guia ilustrado e acessível sobre como os filmes são feitos, da ideia inicial e do roteiro ao elenco, filmagem, edição e lançamento.","Physical"),
 b("thinking-fast-and-slow","Thinking, Fast and Slow","Daniel Kahneman",2011,"psy",
   "The Nobel laureate's tour of the two systems that drive how we think, the fast intuitive one and the slow deliberate one, and the biases that trip us up.",
   "O passeio do Nobel de Economia pelos dois sistemas que orientam nosso pensamento, o rápido e intuitivo e o lento e deliberado, e pelos vieses que nos enganam.","Libby","Rápido e Devagar: Duas Formas de Pensar"),
 b("almanack-of-naval-ravikant","The Almanack of Naval Ravikant","Eric Jorgenson",2020,"self",
   "A curated collection of Naval Ravikant's ideas on building wealth and finding happiness, compiled from his tweets, essays and interviews.",
   "Uma coletânea das ideias de Naval Ravikant sobre construir riqueza e encontrar felicidade, organizada a partir de seus tweets, ensaios e entrevistas.","Libby","O Almanaque de Naval Ravikant"),
 b("so-good-they-cant-ignore-you","So Good They Can't Ignore You","Cal Newport",2012,"career",
   "Challenges the 'follow your passion' advice: passion follows mastery, and career capital is what gets you work you love.",
   "Questiona o conselho de 'seguir sua paixão': a paixão vem com a maestria, e o capital de carreira é o que leva ao trabalho que você ama.","Libby"),
 b("recursion","Recursion","Blake Crouch",2019,"fic",
   "A sci-fi thriller about false memory syndrome, a neuroscientist's device and a detective who realizes reality is being rewritten.",
   "Um thriller de ficção científica sobre a síndrome da falsa memória, o aparelho de uma neurocientista e um detetive que percebe que a realidade está sendo reescrita.","Libby"),
 b("digital-minimalism","Digital Minimalism","Cal Newport",2019,"prod",
   "A philosophy of technology use: focus your time on a small number of carefully chosen tools that support what you value, and drop the rest.",
   "Uma filosofia de uso da tecnologia: concentrar o tempo em poucas ferramentas escolhidas com cuidado que apoiam o que você valoriza, e abandonar o resto.","Libby","Minimalismo Digital"),
 b("tiny-experiments","Tiny Experiments","Anne-Laure Le Cunff",2025,"self",
   "How to live freely in a goal-obsessed world: swap rigid goals for small, curious experiments and learn from the results.",
   "Como viver com liberdade em um mundo obcecado por metas: trocar objetivos rígidos por pequenos experimentos curiosos e aprender com os resultados.","Libby"),
 b("outlive","Outlive","Peter Attia",2023,"health",
   "The science and art of longevity: a framework for extending both lifespan and healthspan through exercise, nutrition, sleep and emotional health.",
   "A ciência e a arte da longevidade: um método para ampliar tanto a duração quanto a qualidade da vida por meio de exercício, nutrição, sono e saúde emocional.","Libby","Outlive: A Arte e a Ciência de Viver Mais e Melhor"),
 b("effortless","Effortless","Greg McKeown",2021,"prod",
   "The follow-up to Essentialism: how to make the most important things easier by removing friction and finding effortless ways to get results.",
   "A sequência de Essencialismo: como tornar mais fácil o que mais importa, removendo atrito e encontrando maneiras leves de chegar aos resultados.","Libby"),
 b("bullet-journal-method","The Bullet Journal Method","Ryder Carroll",2018,"prod",
   "The creator of the Bullet Journal explains his analog system to track the past, order the present and plan the future.",
   "O criador do Bullet Journal explica seu sistema analógico para registrar o passado, organizar o presente e planejar o futuro.","Libby","O Método Bullet Journal"),
 b("co-intelligence","Co-Intelligence","Ethan Mollick",2024,"tech",
   "A practical guide to living and working with AI as a collaborator: four rules for co-intelligence and what it means for work, education and creativity.",
   "Um guia prático para viver e trabalhar com IA como parceira: quatro regras para a cointeligência e o que ela significa para trabalho, educação e criatividade.","Libby"),
 b("good-writing","Good Writing","Neal Allen",2026,"write",
   "36 ways to improve your sentences, with examples for each rule and essays on the practicalities of finishing projects and trusting editors.",
   "36 maneiras de melhorar suas frases, com exemplos para cada regra e ensaios sobre os detalhes práticos de terminar projetos e confiar em editores.","Libby"),
 b("protocols","Protocols","Andrew Huberman",2025,"health",
   "An operating manual for the human body: science-based protocols for sleep, focus, stress, fitness and more.",
   "Um manual de operação do corpo humano: protocolos baseados em ciência para sono, foco, estresse, condicionamento físico e mais.","Libby"),
 b("jab-jab-jab-right-hook","Jab, Jab, Jab, Right Hook","Gary Vaynerchuk",2013,"mkt",
   "How to tell your story in a noisy social world: give value with several 'jabs' before you land the 'right hook' ask, tailored to each platform.",
   "Como contar sua história em um mundo social barulhento: entregar valor com vários 'jabs' antes de dar o 'direto' da venda, adaptando-se a cada plataforma.","Kobo Store"),
 b("on-writing-well","On Writing Well","William Zinsser",1976,"write",
   "The classic guide to writing nonfiction: simplicity, clarity, brevity and humanity, with lessons for essays, memoirs, travel and science writing.",
   "O guia clássico para escrever não ficção: simplicidade, clareza, concisão e humanidade, com lições para ensaios, memórias, viagens e divulgação científica.","Kobo Store"),
 b("write-useful-books","Write Useful Books","Rob Fitzpatrick",2020,"write",
   "A systematic approach to writing nonfiction that actually helps readers, from choosing the outcome to validating the idea and structuring the book.",
   "Uma abordagem sistemática para escrever não ficção que realmente ajude os leitores, da escolha do resultado à validação da ideia e à estrutura do livro.","Kobo Store"),
 b("co-existence","Co-Existence","Ethan Mollick",2026,"tech",
   "Follow-up to Co-Intelligence: on working with AI that is sometimes better than you, keeping your judgment and building a durable human advantage. Out October 20, 2026.",
   "Continuação de Co-Intelligence: sobre trabalhar com uma IA que às vezes é melhor do que você, preservar seu julgamento e construir uma vantagem humana duradoura. Lançamento em 20 de outubro de 2026.","Kobo Store"),
 b("think-like-a-rocket-scientist","Think Like a Rocket Scientist","Ozan Varol",2020,"create",
   "Nine strategies from rocket science, like reasoning from first principles and testing at low risk, that anyone can apply to make giant leaps in work and life.",
   "Nove estratégias da ciência de foguetes, como raciocinar a partir de princípios básicos e testar com baixo risco, que qualquer pessoa pode aplicar para dar grandes saltos no trabalho e na vida.","Kobo Store"),
]

json.dump(READ, open("data/books.json","w"), ensure_ascii=False, indent=2)
json.dump(TBR, open("data/tbr.json","w"), ensure_ascii=False, indent=2)
print(len(READ), len(TBR))
